# Generated by Django 4.2.13 on 2024-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink_hot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'verbose_name': ' نوشیدنی گرم',
                'verbose_name_plural': 'نوشیدنی گرم',
            },
        ),
        migrations.RenameModel(
            old_name='Drink',
            new_name='Drink_cold',
        ),
        migrations.AlterModelOptions(
            name='drink_cold',
            options={'verbose_name': ' نوشیدنی سرد', 'verbose_name_plural': 'نوشیدنی سرد'},
        ),
    ]
