# Generated by Django 4.2.13 on 2024-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_drink_cold_price_alter_drink_hot_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink_cold',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='drink_hot',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hookah',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
